apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-db

  template:
    metadata:
      labels:
        app: postgres-db

    spec:
      containers:
      - name: postgres
        image: postgres:16

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          value: studentdb

        - name: POSTGRES_USER
          value: student

        - name: POSTGRES_PASSWORD
          value: student123